# Site settings
title: AMGCube
email: info@AMGCube.com
url: "" # 本地调试为空字符串，发布时替换为 https://AMGCube.com
description: "Limited Space, Unlimited Creativity"
keywords: "Prefabricated housing,Modular buildings"
skills: "Builder - Developer - Architect"
meta_author: AMGCube

# Google webmaster tools
google_verify:
bing_verify:

# Contact form:
contact: disabled

# Disqus settings
disqus_shortname: myshortname

# Color settings
color:
  primary: "0056D2" # 主色，亮蓝
  primary-rgb: "0,86,210"
  secondary: "E6E9EF" # 浅灰
  accent: "FFA500" # 橙色
  text-dark: "333333" # 深灰
  text-light: "FFFFFF" # 白色

# Footer settings
footer:
  copyright: © 2024 AMGCube. All rights reserved.
  location: Brisbane, QLD, Australia
  social: Around the Web
  credits: AMGCube is committed to modular building innovations.

# Social networks
social:
  - title: twitter
    url: https://twitter.com/amgcube
  - title: linkedin
    url: https://linkedin.com/company/amgcube
  - title: github
    url: https://github.com/amgcube

# Postal address
address:
  - line: "AMGCube Headquarters"
  - line: "Brisbane, QLD, Australia"

# Build settings
markdown: kramdown
permalink: pretty

# Exclude specific files or directories
exclude: []

# Defaults for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
