# 网站基本信息
title: AMGCube
email: Info@AMGCube.com
description: >
  AMGCube - Limited Space with unlimited Creativity
baseurl: "" # 线上使用根目录
url: "https://amgcube.com" # 网站的自定义域名

# SEO 和社交媒体
keywords: ["装配式建筑", "模块化空间", "AMGCube"]
twitter_username: "" # 如果没有 Twitter，可留空
github_username: ""  # 如果没有使用 GitHub 社交功能，可留空

# 主题配置
theme: minima # 如果使用 minima 主题

# 插件
plugins:
  - jekyll-feed # 如果需要 RSS 订阅功能，可保留
  # 如果不需要其他插件，可以清理此部分

# 构建设置
markdown: kramdown
kramdown:
  input: GFM # 使用 GitHub 风格的 Markdown
highlighter: rouge # 高亮显示代码的工具

# 排除构建的文件或目录（Jekyll 自动忽略）
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - node_modules/
  - vendor/

# 静态资源设置（如果需要自定义）
assets:
  css: assets/css/style.css # 样式文件
  js: assets/js/script.js   # JavaScript 文件

# 自定义变量（可根据需要扩展）
company_name: AMGCube
company_mission: >
  我们致力于通过装配式、模块化建筑技术，为客户创造灵活、高效和经济的空间解决方案。
